-- DDL

CREATE TABLE USERS
(
    ID        INTEGER PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(35) NOT NULL,
    LASTNAME  VARCHAR(35) NOT NULL,
    USERNAME  VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD  VARCHAR(60) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE TRAINEE
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DATEOFBIRTH DATE,
    ADDRESS VARCHAR(100),
    USERID INT,
    FOREIGN KEY (USERID) REFERENCES USERS (ID)
);
CREATE TABLE TRAININGTYPE
(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  TYPENAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE TRAINER
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    SPECIALIZATION INT,
    USERID INT,
    FOREIGN KEY (USERID) REFERENCES USERS (ID),
    FOREIGN KEY (SPECIALIZATION) REFERENCES TRAININGTYPE (ID)
);

CREATE TABLE TRAINING
(
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   TRAINEEID INT,
   TRAINERID INT,
   TRAININGNAME VARCHAR(55) NOT NULL,
   TRAININGTYPEID INT,
   TRAININGDATE DATE NOT NULL,
   TRAININGDURATION DOUBLE NOT NULL,
   FOREIGN KEY (TRAINEEID) REFERENCES TRAINEE(ID),
   FOREIGN KEY (TRAINERID) REFERENCES TRAINER(ID),
   FOREIGN KEY (TRAININGTYPEID) REFERENCES TRAININGTYPE (ID)
);

CREATE TABLE TRAINEE_TRAINER (
    TRAINEE_ID INT NOT NULL,
    TRAINER_ID INT NOT NULL,
    PRIMARY KEY (TRAINEE_ID, TRAINER_ID),
    FOREIGN KEY (TRAINEE_ID) REFERENCES TRAINEE(ID),
    FOREIGN KEY (TRAINER_ID) REFERENCES TRAINER(ID)
);

COMMIT;